server.modules       = ("mod_accesslog", "mod_cgi")

server.document-root = "/var/www/vent/static"
server.errorlog      = "/proc/self/fd/2"
accesslog.filename   = "/proc/self/fd/2"

index-file.names     = ("index.html")

cgi.execute-x-only   = "enable"
cgi.assign           = (".cgi" => "")
